git:
  repo: "https://github.com/tusharbecoding/k8s-manifests" # Git repo URL you want to sync
  branch: "main"
  pollInterval: 10s

kubernetes:
  kubeconfig: "/Users/tusharchopra/.kube/config" # Path to local kubeconfig
