git:
  repo: "https://github.com/yourusername/k8s-manifests"
  branch: "main"
  pollInterval: 10s # Time interval to check for changes

kubernetes:
  kubeconfig: "/path/to/your/kubeconfig" # Path to local kubeconfig
